export enum ActionTypes {
  ADD_TO_FOLLOW = '[ADD_TO_FOLLOW] ADD_TO_FOLLOW',
  ADD_TO_FOLLOW_SUCCESS = '[ADD_TO_FOLLOW] ADD_TO_FOLLOW success',
  ADD_TO_FOLLOW_FAILURE = '[ADD_TO_FOLLOW] ADD_TO_FOLLOW failure',
}
