export enum ActionTypes {
  ADD_TO_FAVORITES = '[ADD_TO_FAVORITES] ADD_TO_FAVORITES',
  ADD_TO_FAVORITES_SUCCESS = '[ADD_TO_FAVORITES] ADD_TO_FAVORITES success',
  ADD_TO_FAVORITES_FAILURE = '[ADD_TO_FAVORITES] ADD_TO_FAVORITES failure',
}
